/* Generated by Cython 0.29.30 */

#ifndef __PYX_HAVE__python__csm__CPP_wrapper__fast
#define __PYX_HAVE__python__csm__CPP_wrapper__fast

#include "Python.h"

#ifndef __PYX_HAVE_API__python__csm__CPP_wrapper__fast

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *calcstate_from_python(PyObject *, int __pyx_skip_dispatch);

#endif /* !__PYX_HAVE_API__python__csm__CPP_wrapper__fast */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initfast(void);
#else
PyMODINIT_FUNC PyInit_fast(void);
#endif

#endif /* !__PYX_HAVE__python__csm__CPP_wrapper__fast */
