#fortran
FORTRAN = gfortran

# the compiler flags
# FLAGS = -O3 -fno-range-check 
FLAGS = -O3 -fno-range-check -fconvert=big-endian

# the first target. All executables will be made when 'make' is
# invoked with no target
all: mir_big inv_big c2_big

c2_big: c2_3d_symmetry.f
	$(FORTRAN) $(FLAGS) $^ -o $@

inv_big: inv3d_symmetry.f
	$(FORTRAN) $(FLAGS) $^ -o $@

mir_big: mir3d_symmetry.f
	$(FORTRAN) $(FLAGS) $^  -o $@

clean:
	rm -f c2_big mir_big inv_big
