# the compiler
CC = gcc
CXX = g++

# the compiler flags
CFLAGS = -Wall -g -I.
CXXFLAGS = -Wall -g -I.

LFLAGS = -lm  -g

BIN = bin

MOMENT_OBJ = MomentEq.o
RATE_OBJ = RateEq.o
PAIRS_OBJ = PairEq.o

# the first target. All executables will be made when 'make' is
# invoked with no target
all: moment rate pairs

# general rule how to compile a source file and produce an object file
%.c,%.o:
	$(CXX) $(CFLAGS) -c $<

%.cpp,%.o:
	$(CXX) $(CFLAGS) -c $<

# linking rule for the first executable

moment: $(MOMENT_OBJ)
	$(CXX) $(LFLAGS)  $(MOMENT_OBJ) -o $(BIN)/$@	

rate: $(RATE_OBJ)
	$(CXX) $(LFLAGS)  $(RATE_OBJ) -o $(BIN)/$@

pairs: $(PAIRS_OBJ)
	$(CXX) $(LFLAGS)  $(PAIRS_OBJ) -o $(BIN)/$@

# remove object files and backups
clean:
	rm -f *.o *~ 

# DO NOT DELETE

RateEq.o: rk_solver.h equation_set.h vm/vec_mat.h /usr/include/sys/stat.h
RateEq.o: /usr/include/_ansi.h /usr/include/newlib.h
RateEq.o: /usr/include/sys/config.h /usr/include/machine/ieeefp.h
RateEq.o: /usr/include/time.h /usr/include/sys/reent.h
RateEq.o: /usr/include/sys/_types.h /usr/include/sys/lock.h
RateEq.o: /usr/lib/gcc/i686-pc-cygwin/3.4.4/include/stddef.h
RateEq.o: /usr/include/machine/time.h /usr/include/sys/types.h
RateEq.o: /usr/include/machine/_types.h /usr/include/limits.h
RateEq.o: /usr/include/features.h /usr/include/sys/cdefs.h
RateEq.o: /usr/include/sys/features.h /usr/include/machine/types.h
RateEq.o: vm/vm_traits.h vm/vector.h vm/matrix.h vm/vm_types.h vm/vm_math.h
RateEq.o: vm/vm_math.cpp vm/vm_tools.h vm/vm_tools.cpp vm/vm_io.h
RateEq.o: vm/vm_io.cpp /usr/include/math.h
