#!/bin/bash
set -x
BASE_DIR=../../..
OPENBABEL_DIR=$BASE_DIR/openbabel
BUILD_DIR=$OPENBABEL_DIR/build
INSTALL_DIR=`pwd`

if [ ! -d "$OPENBABEL_DIR" ]; then
    while true; do
        read -p "OpenBabel cannot be found. Clone git repository? " yn
        case $yn in
    	    [Yy]* ) break;;
    	    [Nn]* ) echo "Stopping right here"; exit;;
            * ) echo Please answer Yes or No
       esac
    done
    git clone git://github.com/openbabel/openbabel.git $OPENBABEL_DIR
fi

if [ ! -d $BUILD_DIR ]; then
    mkdir $BUILD_DIR
fi

cd $BUILD_DIR
cmake .. -DCMAKE_INSTALL_PATH=$INSTALL_DIR
make
make install

