#!/bin/bash
BASE_DIR=`pwd`
OPENBABEL_DIR=$BASE_DIR/src
BUILD_DIR=$OPENBABEL_DIR/build
INSTALL_DIR=`pwd`

if [ ! -d "$OPENBABEL_DIR" ]; then
    echo Cloning the OpenBabel repository
    git clone git://github.com/openbabel/openbabel.git $OPENBABEL_DIR
fi

if [ ! -d $BUILD_DIR ]; then
    mkdir $BUILD_DIR
fi

cd $BUILD_DIR
echo Running CMAKE
cmake .. -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DOB_MODULE_PATH=$INSTALL_DIR/lib/openbabel/2.3.90
echo Compiling OpenBabel
make -j4
echo Installing OpenBabel
make install
echo Done.
