function res = master_equations(t, y, params)
indices = [0, ((1:length(y)) - 1), 0, 0];
y = [0, y, 0, 0];
res = params.F .* (y(1:end - 3) - y(2:end - 2)) ...
    + params.W .* (indices(3:end-1).*y(3:end-1) - indices(2:end-2).*y(2:end-2))...
    + params.K .* (indices(4:end).*indices(3:end - 1).*y(4:end) - ...
        indices(2:end-2).*indices(1:end-3).*y(2:end-2));