#!/bin/bash
BASE_DIR=`pwd`
OPENBABEL_DIR=$BASE_DIR/src
BUILD_DIR=$OPENBABEL_DIR/build
INSTALL_DIR=`pwd`

unamestr=`uname`
if [[ "$unamestr" == 'Darwin' ]]; then
	echo Using the Bleeding-Edge OpenBabel
	BABEL_VERSION=2.3.9
else
	echo Using OpenBabel 2.3.2
	BABEL_VERSION=2.3.2
fi

if [ ! -d "$OPENBABEL_DIR" ]; then
	if [[ "$BABEL_VERSION" == "2.3.9" ]]; then
		echo Cloning the OpenBabel repository
		git clone https://github.com/openbabel/openbabel.git $OPENBABEL_DIR
	else
	    echo Getting OpenBabel $BABEL_VERSION
	    wget http://downloads.sourceforge.net/project/openbabel/openbabel/$BABEL_VERSION/openbabel-$BABEL_VERSION.tar.gz
	    tar xvf openbabel-$BABEL_VERSION.tar.gz
	    rm openbabel-$BABEL_VERSION.tar.gz
	    mv openbabel-$BABEL_VERSION $OPENBABEL_DIR
	fi
fi

if [ ! -d $BUILD_DIR ]; then
    mkdir $BUILD_DIR
fi

cd $BUILD_DIR
echo Running CMAKE
cmake .. -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DOB_MODULE_PATH=$INSTALL_DIR/lib/openbabel/$BABEL_VERSION
echo Compiling OpenBabel
make -j4
echo Installing OpenBabel
make install
# Taken from here: http://stackoverflow.com/a/4479619/871910
profile_file="$HOME/.bashrc"
if ! grep -q $INSTALL_DIR ${profile_file} ; then
    echo Setting the .bashrc file
    cat << EOT >> ${profile_file}

# Set up the CSM OpenBabel libraries
export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:$INSTALL_DIR/lib
EOT
	echo LD_LIBRARY_PATH was updated. Please run 'source ~/.bashrc'
fi
echo Done.

