#!/bin/bash
BASE_DIR=`pwd`
OPENBABEL_DIR=$BASE_DIR/src
BUILD_DIR=$OPENBABEL_DIR/build
INSTALL_DIR=`pwd`

if [ ! -d "$OPENBABEL_DIR" ]; then
    echo Getting OpenBabel 2.3.2
    wget http://downloads.sourceforge.net/project/openbabel/openbabel/2.3.2/openbabel-2.3.2.tar.gz
    tar xvf openbabel-2.3.2.tar.gz
    rm openbabel-2.3.2.tar.gz
    mv openbabel-2.3.2 $OPENBABEL_DIR
fi

if [ ! -d $BUILD_DIR ]; then
    mkdir $BUILD_DIR
fi

cd $BUILD_DIR
echo Running CMAKE
cmake .. -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DOB_MODULE_PATH=$INSTALL_DIR/lib/openbabel/2.3.2
echo Compiling OpenBabel
make -j4
echo Installing OpenBabel
make install
# Taken from here: http://stackoverflow.com/a/4479619/871910
profile_file="$HOME/.bashrc"
if ! grep -q $INSTALL_DIR ${profile_file} ; then
    echo Setting the .bashrc file
    cat << EOT >> ${profile_file}

# Set up the CSM OpenBabel libraries
export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:$INSTALL_DIR/lib
EOT
	echo LD_LIBRARY_PATH was updated. Please run 'source ~/.bashrc'
fi
echo Done.

